version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build"
    target-branch: "develop"
    schedule:
      interval: "daily"